export const GET_MAP_ID = 'GET_MAP_ID';
export const GET_UPLOAD_ID = 'GET_UPLOAD_ID';
export const SET_UPLOAD_ID = 'SET_UPLOAD_ID';
export const SET_UPLOAD_STATUS = 'SET_UPLOAD_STATUS';
export const GET_UPLOAD_STATUS = 'GET_UPLOAD_STATUS';
export const GET_UPLOAD_COUNT = 'GET_UPLOAD_COUNT';
export const SET_UPLOAD_COUNT = 'SET_UPLOAD_COUNT';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const SET_SERVER_URL = 'SET_SERVER_URL';
export const GET_SERVER_URL = 'GET_SERVER_URL';
export const CONFIGURE_SUCCESS = 'CONFIGURE_SUCCESS';
export const UPLOADED_DATA_SUCCESS = 'UPLOADED_DATA_SUCCESS';
export const IMPORT_ALL_SUCCESS = 'IMPORT_ALL_SUCCESS';

